version: "1"
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - database
  database:
    image: mariadb:latest
    volumes:
      - ./back-end/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=dev1234
      - MYSQL_DATABASE=dakee
